import Head from 'next/head';
import Modal from '@/components/Modal';
import SettingsBlock from '@/components/SettingsBlock';
import { useDispatch } from 'react-redux';
import { setModalState } from '@/redux/global/actions';

export default function Home() {
  const dispatch = useDispatch();

  const sections = [
    {
      title: 'Account',
      content: (
        <SettingsBlock icon="dog" isBoolean={false}>
          Personal Info
        </SettingsBlock>
      ),
    },
    {
      title: 'Settings',
      content: (
        <>
          <SettingsBlock icon="alert">Notifications</SettingsBlock>
          <SettingsBlock icon="dark" isBoolean={true}>
            Dark Mode
          </SettingsBlock>
          <SettingsBlock icon="language">Language</SettingsBlock>
        </>
      ),
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Modal sections={sections} />
        <div className="w-screen h-screen bg-black flex flex-wrap justify-center items-center gap-3">
          <p
            className="px-9 py-3 border-2 text-primary-700 font-bold hover:bg-primary-700 hover:text-white border-primary-700 rounded-lg cursor-pointer"
            onClick={() => dispatch(setModalState(true))}
          >
            Open Modal
          </p>
        </div>
      </main>
    </>
  );
}
